version: "3.9"

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: chat-postgres
    environment:
      POSTGRES_USER: chatapp
      POSTGRES_PASSWORD: chatapp
      POSTGRES_DB: chatapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatapp -d chatapp"]
      interval: 5s
      timeout: 3s
      retries: 20

  rabbitmq:
    image: rabbitmq:3-management
    container_name: chat-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  backend-api:
    build:
      context: ./backend/ChatApp
      dockerfile: Dockerfile
    container_name: chat-api
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080

      # Npgsql (dentro do Docker: use Host=postgres-db)
      ConnectionStrings__DefaultConnection: Host=postgres-db;Port=5432;Database=chatapp;Username=chatapp;Password=chatapp

      # RabbitMQ
      RabbitMQ__Host: rabbitmq

      # JWT (Options Pattern lê via IConfiguration)
      JWT__ValidIssuer: ChatApp
      JWT__ValidAudience: ChatApp.Api
      JWT__SecretKey: ${JWT_SECRET}
      JWT__TokenValidityInMinutes: "30"
      JWT__RefreshTokenValidityInMinutes: "60"

    depends_on:
      postgres-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started

volumes:
  pgdata:
